// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4cOkXEb5ZGBqkIgNz9ueaNOKelHqFZg4',
    appId: '1:11563356982:web:b6d4a3212065500507d997',
    messagingSenderId: '11563356982',
    projectId: 'step-chat-ag-1764700261',
    authDomain: 'step-chat-ag-1764700261.firebaseapp.com',
    storageBucket: 'step-chat-ag-1764700261.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-GM7FYC7P4-PPfkz9eqosZz4i09aWqfM',
    appId: '1:11563356982:android:cee82db5bdf5183707d997',
    messagingSenderId: '11563356982',
    projectId: 'step-chat-ag-1764700261',
    storageBucket: 'step-chat-ag-1764700261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Wj_pG-Wz0txfEzYI6_cn7AkcsE0AhPg',
    appId: '1:11563356982:ios:c58ced1d52164f4f07d997',
    messagingSenderId: '11563356982',
    projectId: 'step-chat-ag-1764700261',
    storageBucket: 'step-chat-ag-1764700261.firebasestorage.app',
    iosBundleId: 'com.example.stepChat',
  );
}
